In [1]:
open('test.txt', 'wb').write(bytes([65, 66, 67, 255, 192,193]))
open(filename, encoding='Windows-1252', errors='ignore')


6

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

In [7]:
tf_matrix = vectorizer.fit_transform(newsgroups.data)
print(tf_matrix)

  (0, 108644)	4
  (0, 110106)	1
  (0, 57577)	2
  (0, 24398)	2
  (0, 79534)	1
  (0, 100942)	1
  (0, 37154)	1
  (0, 45141)	1
  (0, 70570)	1
  (0, 78701)	2
  (0, 101084)	4
  (0, 32499)	4
  (0, 92157)	1
  (0, 100827)	6
  (0, 79461)	1
  (0, 39275)	1
  (0, 60326)	2
  (0, 42332)	1
  (0, 96432)	1
  (0, 67137)	1
  (0, 101732)	1
  (0, 27703)	1
  (0, 49871)	2
  (0, 65338)	1
  (0, 14106)	1
  :	:
  (11313, 55901)	1
  (11313, 93448)	1
  (11313, 97535)	1
  (11313, 93393)	1
  (11313, 109366)	1
  (11313, 102215)	1
  (11313, 29148)	1
  (11313, 26901)	1
  (11313, 94401)	1
  (11313, 89686)	1
  (11313, 80827)	1
  (11313, 72219)	1
  (11313, 32984)	1
  (11313, 82912)	1
  (11313, 99934)	1
  (11313, 96505)	1
  (11313, 72102)	1
  (11313, 32981)	1
  (11313, 82692)	1
  (11313, 101854)	1
  (11313, 66399)	1
  (11313, 63405)	1
  (11313, 61366)	1
  (11313, 7462)	1
  (11313, 109600)	1


In [34]:
import pandas as pd
import numpy as np



In [35]:
from xml.etree.ElementTree import parse
document = parse('blogs/5114.male.25.indUnk.Scorpio.xml')


ParseError: not well-formed (invalid token): line 965, column 585 (<string>)

In [111]:
import bs4 as bs
import re

#filename = 'blogs/11253.male.26.Technology.Aquarius.xml'
filename = 'blogs/5114.male.25.indUnk.Scorpio.xml'
filenameAssert = re.search("^.*\D\d{2}\D.*xml$", filename)
assert filenameAssert != None 


#assert filename.contains
#source = open('blogs/5114.male.25.indUnk.Scorpio.xml').read()
source = open(filename).read()

soup = bs.BeautifulSoup(source, "lxml")
posts = soup.find_all("post")
dates = soup.find_all("date")
print(posts[0])

post = posts[0].text

assert "Slashdot raises lots of " in post




<post>


       
      Slashdot raises lots of  urlLink interesting thoughts about banner ads .  The idea is to let users control the ad delivery, and even to allow users to comment on ads.
     

    
</post>


In [143]:
d = {'post': posts, 'date': dates}
df = pd.DataFrame(data=d)
df

post  \
0    [\n\n\n       \n      Slashdot raises lots of ...   
1    [\n\n\n       \n       urlLink  The Merchants ...   
2    [\n\n\n       \n       urlLink ATMs dispensing...   
3    [\n\n\n       \n      My chair started squeaki...   
4    [\n\n\n       \n      The New York Press has a...   
..                                                 ...   
193  [\n\n\n       \n      I'm looking for someone ...   
194  [\n\n\n       \n      I'm pleased to announce ...   
195  [\n\n\n       \n      I'm using this blog to p...   
196  [\n\n\n       \n      I'm blogging a lot more ...   
197  [[\n\n\n       \n      Slashdot raises lots of...   

                                                  date  
0                                   [28,February,2001]  
1                                   [27,February,2001]  
2                                   [26,February,2001]  
3                                   [22,February,2001]  
4                                   [20,February,2001]  
..                                                 ...  
193                                    [06,April,2004]  
194                                      [17,May,2004]  
195                                      [10,May,2004]  
196                                     [28,June,2004]  
197  [[28,February,2001], [27,February,2001], [26,F...  

[198 rows x 2 columns]

In [139]:
df.shape

(197, 2)

In [190]:
import chardet
import glob
from chardet.universaldetector import UniversalDetector

authorIDs = [3574878, 2845196, 3444474, 3445677, 828046, 4284264, 3498812, 4137740, 3662461, 3363271]
filenames = []

detector = UniversalDetector()

for id in authorIDs:
 filename = glob.glob('blogs/' + str(id) + '.*.xml')
 filenames.append(filename[0])
    
for filename in filenames:
#for filename in glob.glob('blogs/*.xml'):
    print(filename)
    detector.reset()
    for line in open(filename, 'rb'):
        detector.feed(line)
        if detector.done: break
    detector.close()
    print(detector.result)

  (0, 108644)	4
  (0, 110106)	1
  (0, 57577)	2
  (0, 24398)	2
  (0, 79534)	1
  (0, 100942)	1
  (0, 37154)	1
  (0, 45141)	1
  (0, 70570)	1
  (0, 78701)	2
  (0, 101084)	4
  (0, 32499)	4
  (0, 92157)	1
  (0, 100827)	6
  (0, 79461)	1
  (0, 39275)	1
  (0, 60326)	2
  (0, 42332)	1
  (0, 96432)	1
  (0, 67137)	1
  (0, 101732)	1
  (0, 27703)	1
  (0, 49871)	2
  (0, 65338)	1
  (0, 14106)	1
  :	:
  (11313, 55901)	1
  (11313, 93448)	1
  (11313, 97535)	1
  (11313, 93393)	1
  (11313, 109366)	1
  (11313, 102215)	1
  (11313, 29148)	1
  (11313, 26901)	1
  (11313, 94401)	1
  (11313, 89686)	1
  (11313, 80827)	1
  (11313, 72219)	1
  (11313, 32984)	1
  (11313, 82912)	1
  (11313, 99934)	1
  (11313, 96505)	1
  (11313, 72102)	1
  (11313, 32981)	1
  (11313, 82692)	1
  (11313, 101854)	1
  (11313, 66399)	1
  (11313, 63405)	1
  (11313, 61366)	1
  (11313, 7462)	1
  (11313, 109600)	1


In [240]:
filenames = []
for filename in glob.glob('blogs/*'):
 filenames.append(filename)

data = []
all_posts = []
for filename in filenames[0:100]:
    #print(filename)
    source = open(filename, errors='replace').read()
    soup = bs.BeautifulSoup(source, "xml")
    posts = soup.find_all("post")
    dates = soup.find_all("date")
    for i in range(1, len(posts)):
         data.append({'blog': filename, 'posts': posts[i].text, 'dates': dates[i].text})
         all_posts.append(posts[i].text)

In [241]:


df = pd.DataFrame(data=data)
df

blog  \
0               blogs\1000331.female.37.indUnk.Leo.xml   
1               blogs\1000331.female.37.indUnk.Leo.xml   
2               blogs\1000331.female.37.indUnk.Leo.xml   
3               blogs\1000331.female.37.indUnk.Leo.xml   
4               blogs\1000331.female.37.indUnk.Leo.xml   
...                                                ...   
15909  blogs\1089670.female.17.Student.Sagittarius.xml   
15910      blogs\1090235.female.17.indUnk.Aquarius.xml   
15911      blogs\1090235.female.17.indUnk.Aquarius.xml   
15912      blogs\1090235.female.17.indUnk.Aquarius.xml   
15913     blogs\1090547.male.14.Religion.Capricorn.xml   

                                                   posts            dates  
0      \n\n\t \n      My four-year old never stops ta...      29,May,2004  
1      \n\n\t \n      Actually it's not raining yet, ...      28,May,2004  
2      \n\n\t \n      Ha! Just set up my RSS feed - t...      28,May,2004  
3      \n\n\t \n      Oh, which just reminded me, we ...      28,May,2004  
4      \n\n\t \n      I've tried starting blog after ...      28,May,2004  
...                                                  ...              ...  
15909  \n\n     \n      Sum1 told me about "Hope" rec...   04,August,2004  
15910  \n\n\t \n       wow im writing twice in 2 days...   07,August,2004  
15911  \n\n\t \n       heyyy :) whats up? it is frida...   06,August,2004  
15912  \n\n\t \n       things are about to change dra...   03,August,2004  
15913  \n\n\t \n       prounced: "pett-it"   Alright,...  09,juillet,2004  

[15914 rows x 3 columns]

In [243]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
tf_matrix = vectorizer.fit_transform(all_posts)
print(tf_matrix)

  (0, 37733)	1
  (0, 22590)	1
  (0, 63031)	1
  (0, 39757)	1
  (0, 38474)	1
  (0, 53834)	1
  (0, 55456)	1
  (0, 50360)	2
  (0, 33509)	2
  (0, 49046)	3
  (0, 36817)	1
  (0, 3876)	1
  (0, 61600)	1
  (0, 63101)	1
  (0, 58596)	2
  (0, 39679)	1
  (0, 63019)	1
  (0, 61610)	1
  (0, 17292)	1
  (0, 32238)	1
  (0, 9066)	1
  (0, 26750)	1
  (0, 28595)	1
  (0, 56245)	1
  (0, 45475)	1
  :	:
  (15913, 49398)	1
  (15913, 17866)	1
  (15913, 19059)	1
  (15913, 18799)	1
  (15913, 60662)	1
  (15913, 37825)	1
  (15913, 33873)	1
  (15913, 5627)	1
  (15913, 21311)	1
  (15913, 7158)	1
  (15913, 25425)	1
  (15913, 61398)	1
  (15913, 14839)	1
  (15913, 44596)	1
  (15913, 42225)	1
  (15913, 21290)	4
  (15913, 17302)	2
  (15913, 21291)	1
  (15913, 42230)	4
  (15913, 31901)	1
  (15913, 45187)	2
  (15913, 49198)	1
  (15913, 44921)	1
  (15913, 56336)	1
  (15913, 638)	1


In [244]:
tf_np_matrix = tf_matrix.toarray()
print(tf_np_matrix)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [248]:

num_posts, vocabulary_size = tf_matrix.shape
print(f"Our collection of {num_posts} newsgroup posts contain a total of "
      f"{vocabulary_size} unique words")

import numpy as np
tf_vector = tf_np_matrix[0]
non_zero_indices = np.flatnonzero(tf_vector)
num_unique_words = non_zero_indices.size
print(f"The newsgroup in row 0 contains {num_unique_words} unique words.")
print("The actual word-counts map to the following column indices:\n")
print(non_zero_indices)

words = vectorizer.get_feature_names()
unique_words = [words[i] for i in non_zero_indices]
print(unique_words)

import pandas as pd
data = {'Word': unique_words,
        'Count': tf_vector[non_zero_indices]}

df = pd.DataFrame(data).sort_values('Count', ascending=False)
print(df[:10].to_string(index=False))

Our collection of 15914 newsgroup posts contain a total of 63921 unique words
The newsgroup in row 0 contains 41 unique words.
The actual word-counts map to the following column indices:

[ 3876  4261  9066 17292 20346 22590 24289 26302 26590 26750 28595 29970
 32238 33509 36817 37733 38474 39145 39679 39757 40773 45475 46762 49046
 50360 50982 53834 55456 56245 56474 57002 58596 60143 60508 61600 61610
 61842 62433 63019 63031 63101]
['and', 'anything', 'bugs', 'do', 'exhausting', 'four', 'go', 'hear', 'her', 'hide', 'in', 'is', 'lady', 'll', 'mom', 'my', 'never', 'now', 'oh', 'old', 'own', 'rain', 'remember', 'say', 'she', 'sigh', 'stops', 'talking', 'the', 'this', 'to', 'ummm', 'very', 'voice', 'when', 'where', 'why', 'work', 'yeah', 'year', 'yes']
    Word  Count
     say      3
    ummm      2
      to      2
     she      2
      ll      2
    very      2
    sigh      1
   stops      1
 talking      1
     the      1
